[package]
name = "jeera"
version = "0.1.0"
authors = ["Peter Salvatore <peter@psftw.com>"]
edition = "2018"

[dependencies]
dirs = "1.0"
goji = "^0.2"
prettytable-rs = "^0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
structopt = "0.2"
